import requiredArgs from '../_lib/requiredArgs/index'
import getDay from '../getDay'
import addDays from '../addDays'

const baseMap = [7, 6, 5, 4, 3, 2, 1] // 0 day

/**
 * @name nextDayOfWeek
 * @category Weekday Helpers
 * @summary When is the next day of Week?
 *
 * @description
 * When is the next day of week?
 * {0|1|2|3|4|5|6} the day of week, 0 represents Sunday
 *
 * The following maps will be generated by genMap()
 * const mapSunday = [7, 6, 5, 4, 3, 2, 1] // 0 day
 * const mapMonday = [1, 7, 6, 5, 4, 3, 2] // 1 day
 * const mapTuesday = [2, 1, 7, 6, 5, 4, 3] // 2 day
 * const mapWednesday = [3, 2, 1, 7, 6, 5, 4] // 3 day
 * const mapThursday = [4, 3, 2, 1, 7, 6, 5] // 4 day
 * const mapFriday = [5, 4, 3, 2, 1, 7, 6] // 5 day
 * const mapSaturday = [6, 5, 4, 3, 2, 1, 7] // 6 day
 *
 * @param {Date} date - the date to check
 * @returns {Date} the date is the day of week
 * @throws {TypeError} 2 arguments required
 *
 * @example
 * When is the next Monday after Mar, 22, 2020?
 * var result = nextMonday(new Date(2020, 2, 22), 1)
 * => new Date(2020, 2, 23)
 *
 * @example
 * When is the next Tuesday after Mar, 22, 2020?
 * var result = nextMonday(new Date(2020, 2, 22), 2)
 * => new Date(2020, 2, 24)
 **/

const genMap = (daysToMove: number) => {
  if (daysToMove === 0) {
    return baseMap
  } else {
    const mapStart = baseMap.slice(-daysToMove)
    const mapEnd = baseMap.slice(0, baseMap.length - daysToMove)
    return mapStart.concat(mapEnd)
  }
}

export default function nextDayOfWeek(date: Date, day: number): Date {
  requiredArgs(2, arguments)
  const map = genMap(day)
  return addDays(date, map[getDay(date)])
}
