export const daysInWeek: number
export const maxTime: number
export const millisecondsInMinute: number
export const millisecondsInHour: number
export const millisecondsInSecond: number
export const minTime: number
export const minutesInHour: number
export const monthsInQuarter: number
export const monthsInYear: number
export const quartersInYear: number
export const secondsInHour: number
export const secondsInMinute: number
