var CONSTANTS = require('../_lib/constants')
var TIME_DESIGNATOR = CONSTANTS.TIME_DESIGNATOR
var PERIOD_DESIGNATOR = CONSTANTS.PERIOD_DESIGNATOR

var MATCH_NUMBER = /[+-]?\d+(\.\d+)?/.source

var MATCH_YEARS = '(' + MATCH_NUMBER + CONSTANTS.YEARS + ')?'
var MATCH_MONTHS = '(' + MATCH_NUMBER + CONSTANTS.MONTHS + ')?'
var MATCH_WEEKS = '(' + MATCH_NUMBER + CONSTANTS.WEEKS + ')?'
var MATCH_DAYS = '(' + MATCH_NUMBER + CONSTANTS.DAYS + ')?'
var MATCH_HOURS = '(' + MATCH_NUMBER + CONSTANTS.HOURS + ')?'
var MATCH_MINUTES = '(' + MATCH_NUMBER + CONSTANTS.MINUTES + ')?'
var MATCH_SECONDS = '(' + MATCH_NUMBER + CONSTANTS.SECONDS + ')?'

var MATCH_DATE = MATCH_YEARS + MATCH_MONTHS + MATCH_WEEKS + MATCH_DAYS
var MATCH_TIME = '(' + TIME_DESIGNATOR + MATCH_HOURS + MATCH_MINUTES + MATCH_SECONDS + ')?'
var MATCH_DURATION = new RegExp('^' + PERIOD_DESIGNATOR + MATCH_DATE + MATCH_TIME + '$')

function isValid (isoDuration) {
  return MATCH_DURATION.test(isoDuration.toUpperCase())
}

module.exports = isValid
