name: Coverage report

on: workflow_dispatch
# on:
#   push:
#     branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 22
      - run: pnpm install
      - run: pnpm vitest run --coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
