name: Coverage report

on: workflow_dispatch
# on:
#   push:
#     branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: pnpm install

      # TODO: Enable or remove
      - run: pnpm vitest run --coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
