name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          # TODO: rename azure-pipelines/linux/xvfb.init to github-actions
      - run: |
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
          sudo chmod +x /etc/init.d/xvfb
          sudo update-rc.d xvfb defaults
          sudo service xvfb start
      - name: export CHROME_BIN
        run: export CHROME_BIN=chromium-browser
      - name: export DISPLAY
        run: export DISPLAY=:99.0
      - name: Install yarn
        run: npm install -g yarn
      # - name: Build and Test
      #   run: ./scripts/test/travis.sh
