name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: export CHROME_BIN
        run: export CHROME_BIN=chromium-browser
      - name: export DISPLAY
        run: export DISPLAY=:99.0
      - name: sh
        run: sh -e /etc/init.d/xvfb start
      - name: Install yarn
        run: npm install -g yarn
      # - name: Build and Test
      #   run: ./scripts/test/travis.sh
