name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Before install
        run: export CHROME_BIN=chromium-browser
        run: export DISPLAY=:99.0
        run: sh -e /etc/init.d/xvfb start
        run: npm install -g yarn
      - name: Build and Test
        run: ./scripts/test/travis.sh
        
